"""first migrate

Revision ID: b3114d43d2d2
Revises: 
Create Date: 2020-02-09 23:02:41.597176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3114d43d2d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('job', sa.String(length=256), nullable=True),
    sa.Column('company', sa.String(length=256), nullable=True),
    sa.Column('ssn', sa.String(length=256), nullable=True),
    sa.Column('residence', sa.Text(), nullable=True),
    sa.Column('current_location', sa.String(length=10), nullable=True),
    sa.Column('blood_group', sa.String(length=3), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('sex', sa.String(length=1), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('mail', sa.String(length=256), nullable=True),
    sa.Column('birthdate', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persons')
    # ### end Alembic commands ###
